apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: krateo-template-aws-stack
  annotations:
    meta.crossplane.io/maintainer: Diego Braga <diego.braga@kiratech,it>
    meta.crossplane.io/keywords: krateo, aws, template, kubernetes, platform, reference
    meta.crossplane.io/source: github.com/krateoplatformops/krateo-template-aws-stack
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This reference platform Configuration for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

    meta.crossplane.io/readme: |
      This reference platform `Configuration` for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

      It provides platform APIs to provision fully configured Krateo Core
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - provider: registry.upbound.io/crossplane/provider-aws
      version: ">=v0.25.0-0"
    - provider: ghcr.io/krateoplatformops/krateo-module-core
      version: ">=v0.1.0-294"
