---
apiVersion: templates.krateo.io/v1alpha1
kind: aws-stack
metadata:
  name: "${{ name }}"
spec:
  compositionSelector:
    matchLabels:
      platform: aws
  name: "${{ name }}"
  sysdig:
    accessKey: "13654062-7ef7-4b5f-a28f-fc47dd8c737a"
  eks:
    clusterName: ${{ clusterName }}"
  network:
    networkName: "${{ networkName }}"
  rds:
    region: "${{ rdsRegion }}"
    allocatedStorage: "${{ rdsDataDiskSizeGb }}"
    dbInstanceClass: "${{ rdsInstanceClass }}"
    engineVersion: "${{ rdsEngineVersion }}"
    storageType: "${{ rdsStorageType }}"
