---
apiVersion: templates.krateo.io/v1alpha1
kind: aws-stack
metadata:
  name: aws-stack
spec:
  compositionSelector:
    matchLabels:
      platform: aws
  name: test-aws-meetup
  eks:
    clusterName: test-aws-meetup-eks
  network:
    networkName: test-aws-meetup-network
  rds:
    rdsRegion: eu-central-1
    rdsDataDiskSizeGb: '10'
    rdsInstanceClass: db.t3.micro
    rdsEngineVersion: '13.4'
    rdsStorageType: standard
