---
apiVersion: templates.krateo.io/v1alpha1
kind: aws-stack
metadata:
  name: aws-stack-tigera
spec:
  compositionSelector:
    matchLabels:
      platform: aws
  name: aws-stack-tigera
  eks:
    clusterName: aws-stack-tigera-cluster
  network:
    networkName: aws-stack-tigera-network
  rds:
    region: eu-central-1
    allocatedStorage: 10 #ex dataDiskSizeGb
    dbInstanceClass: db.t3.micro
    engineVersion: '13.4'
    storageType: standard
  fromRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: krateo-template-aws-stack
    organizationName: krateoplatformops
    schema: https
  toRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: aws-stack-tigera-stack
    organizationName: krateoplatformops
    schema: https
