---
apiVersion: templates.krateo.io/v1alpha1
kind: krateo-template-aws-stack
metadata:
  name: krateo-template-aws-stack
spec:
  compositionSelector:
    matchLabels:
      platform: aws
  name: test-aws-meetup
  eks:
    clusterName: test-aws-meetup-eks
  network:
    networkName: test-aws-meetup-network
  rds:
    region: eu-central-1
    allocatedStorage: 10 #ex dataDiskSizeGb
    dbInstanceClass: db.t3.micro
    engineVersion: '13.4'
    storageType: standard
  fromRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: krateo-template-aws-stack
    organizationName: krateoplatformops
    schema: https
  toRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: krateo-template-aws-stack-test-git-provider
    organizationName: krateoplatformops
    schema: https